# Definir la liste des services (container) dont nous aurons besoin

services:
  # Definition du container contenant l'api
  app:
    # build du container à partir du dossier . au travers du dockerfile 'Dockerfile.dev'
    build:
      context: .
      dockerfile: Dockerfile

    command: sh -c "rsync -arv /usr/src/cache/node_modules/. /usr/src/app/node_modules && pnpm run dev"

    # Lier le port 3000 du container au port 3000 local
    ports:
      - 3000:3000

    # Nommer le container
    container_name: petfoster-api

    volumes:
      # mon répertoire de travail perso, avec les sources
      # de mon appli est le répertoire de travail
      # du conteneur
      - ./:/usr/src/app

volumes:
  petfoster-volume:
