services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      -  3000:3000
    container_name: petfoster-api
    depends_on:
      petfoster-db:
       condition: service_healthy
    volumes:
      # mon répertoire de travail perso, avec les sources
      # de mon appli est le répertoire de travail
      # du conteneur
      - ./:/usr/src/app

  petfoster-db:
    image: postgres
    container_name: petfoster-db
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      # - petfoster-volume:/var/lib/postgresql/data


volumes:
  petfoster-volume: